### ISSUE TITLE
XMPP client does not restart after second error in Listen

### ISSUE THREAD

**Issue by kuchlous** [rounds/go-gcm#11]
After an error happens in Listen, the xmpp server is supposed to restart. After the first error, it does indeed restart but after another error, it does not. The result is that the GCM messages do not reach the server anymore.

From the logfiles. At first error:

time="2016-09-14T04:49:38+05:30" level=error msg="gcm xmpp listen" error="error on Recv: XML syntax error on line 1: unexpected EOF" xmpp client ref=0xc820302000
time="2016-09-14T04:49:38+05:30" level=debug msg="gcm xmpp listen finished" xmpp client ref=0xc820302000
time="2016-09-14T04:49:38+05:30" level=warning msg="gcm xmpp connection closed" error="error on Recv: XML syntax error on line 1: unexpected EOF" xmpp client ref=0xc820302000
time="2016-09-14T04:49:38+05:30" level=debug msg="creating gcm xmpp client" sender id=282308463187
<stream:stream from="gcm.googleapis.com" id="9F095DD2A3785B12" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client">
stream:features<mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>X-OAUTH2</mechanism><mechanism>X-GOOGLE-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms>/stream:features
<success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/>
<stream:stream from="gcm.googleapis.com" id="E28A8CE15623D186" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client">
stream:features<bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/>/stream:features
<iq id="9c2e5eb4b23cf415" type="result"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>282308463187@gcm.googleapis.com/DF457434</jid></bind></iq>
time="2016-09-14T04:49:40+05:30" level=warning msg="gcm xmpp client replaced" previous xmpp client ref=0xc820302000 xmpp client ref=0xc8281470e0
time="2016-09-14T04:49:40+05:30" level=debug msg="gcm xmpp listen started" xmpp client ref=0xc8281470e0

At second error:

time="2016-09-14T04:55:46+05:30" level=error msg="gcm xmpp listen" error="error on Recv: XML syntax error on line 1: unexpected EOF" xmpp client ref=0xc8281470e0
time="2016-09-14T04:56:01+05:30" level=debug msg="-- ping" xmpp client id=0xc8281470e0

and no more messages in the logfile from the xmpp server.

**Comment by kuchlous** [comment]
I tried reproducing the problem by using tcpkill but no success. The xmpp client always restarts even after a few errors on Listen because of tcpkill.

**Comment by kuchlous** [comment]
@bolshoy , I was looking at the code and had a question (not related to this problem). When we receive an error in monitorXMPP, we will go through the for loop again, call connectXMPP and and start another instance of pingPeriodically. Should we be disabling the earlier instance of pingPeriodically at that time?

**Comment by bolshoy** [comment]
@kuchlous are you sure you use the latest build? I had this problem a couple of commits back and fixed it, the latest version runs well for a week. What kind of load do you have?

**Comment by bolshoy** [comment]
@kuchlous no need to stop the ping monitor explicitly, the last ping on the dead connection will either time out or return error and the monitor will exit. The downside is keeping the goroutine up for a few extra seconds,.

**Comment by kuchlous** [comment]
I have your changes till the Aug 30th checkin aa5b2ef8faa4e5986af0177cc1ae415890df7b77 .
Is the fix in a change after that? My guess is that for some reason the error channel on which connectXMPP is writing on a Listen error is full and for that reason the process hangs waiting for that channel. I say this because you see the message from before the write on the channel but nothing after that.

I will update my code with your last checkin as well and try.

**Comment by bolshoy** [comment]
@kuchlous I just made some artificial disconnects and got the error you mentioned. Working on this.

**Comment by kuchlous** [comment]
@bolshoy , Thanks. Would love to understand what the problem was.

**Comment by kuchlous** [comment]
@bolshoy , I see some checkins which refer to this issue. Is it fixed? Should I update my code?

**Comment by bolshoy** [comment]
@kuchlous running the new code for several days, no problems meanwhile. Please update and see if it works well for you.

**Comment by kuchlous** [comment]
@bolshoy , I have pulled your changes. Will try and let you know how it
goes. Would be grateful if you can explain what the problem was. I see that
the major change that you made was to add a capacity of '1' to the error
channel.

**Comment by kuchlous** [comment]
@bolshoy , it is working fine so far.

**Comment by bolshoy** [comment]
@kuchlous here too, thanx. I reworked some logic to eliminate possible deadlocks and goroutine blocking  on channels. Looks ok so far, but I am not too content with the code. I am considering eliminating the Listen API in the future and calling listen inside the constructor. It should straighten out some things. wdyt?

**Comment by kuchlous** [comment]
@bolshoy , not clear how that would help but if you explain your motivation
a bit I may be able to give some feedback. Would certainly like to help in
any way I can.

**Comment by bolshoy** [comment]
@kuchlous will straighten up things externally, more foolproof

**Comment by kuchlous** [comment]
This seems to be finally fixed. Have seen this error in the log many times, but the XMPP client restarted each time. So we can close this.

**Comment by bolshoy** [comment]
@kuchlous thanx, runs fine here for two months too, forgot to close it.

**Comment by kuchlous** [comment]
@bolshoy , unrelated note. Do you know of any way to do perf testing with
GCM? I want to perf-test the whole flow, send GCM upstream messages,
process in server and send GCM downstream messages. I am unable to figure
out how to send GCM upstream messages from a script..

**Comment by bolshoy** [comment]
@kuchlous you need an agent that will use google api to send an upstream message from a device, like here: https://firebase.google.com/docs/cloud-messaging/android/upstream
check also: http://www.grokkingandroid.com/upstream_messages_with_google_cloud_messaging/
We don't need it, so I haven't really explored it.

**Comment by kuchlous** [comment]
@bolshoy , thanks for the pointers. Our app is working fine but it is
difficult to generate a large number of messages from device to simulate
reasonable traffic. But anyway, I simulated the upstream traffic over http
in the hope that the http will be slower than XMPP so I have a worst case
scenario.
